name: mmpeg-service
services:
  api:
    build: .
    expose:
      - ${API_PORT}
    tmpfs:
      - /app/tmp:size=1024M
    env_file:
      - .env
    container_name: mmpeg-api
    restart: unless-stopped
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:8.3.4
    container_name: mmpeg-mongo
    expose:
      - 27017
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:8-alpine
    container_name: mmpeg-redis
    expose:
      - 6379
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
