export const ERROR_CODES = {
    INVALID_FILE: 'INVALID_FILE',
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
    INVALID_MEDIA_FORMAT: 'INVALID_MEDIA_FORMAT',
    MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
    MEDIA_HAS_ARTIFACTS: 'MEDIA_HAS_ARTIFACTS',
    ARTIFACT_NOT_FOUND: 'ARTIFACT_NOT_FOUND',
    ARTIFACT_HAS_CHILDREN: 'ARTIFACT_HAS_CHILDREN',
    JOB_NOT_FOUND: 'JOB_NOT_FOUND',
    PROCESSING_FAILED: 'PROCESSING_FAILED',
    FFMPEG_FAILED: 'FFMPEG_FAILED',
    FFPROBE_FAILED: 'FFPROBE_FAILED',
    SIGNED_URL_FAILED: 'SIGNED_URL_FAILED',
    VALIDATION_FAILED: 'VALIDATION_FAILED',
    RATE_LIMITED: 'RATE_LIMITED',
    STORAGE_WRITE_FAILED: 'STORAGE_WRITE_FAILED',
    STORAGE_READ_FAILED: 'STORAGE_READ_FAILED'
};
